export const START_CONNECT_WALLET = 'START_CONNECT_WALLET';
export const CONNECT_WALLET_SUCCESS = 'CONNECT_WALLET_SUCCESS';
export const CONNECT_WALLET_FAILED = 'CONNECT_WALLET_FAILED';
export const STOP_CONNECT_WALLET = 'STOP_CONNECT_WALLET';

export const SET_ACCOUNT = 'SET_ACCOUNT';

export const GET_ALL_WAVES = 'GET_ALL_WAVES';
export const UPDATE_ALL_WAVES = 'UPDATE_ALL_WAVES';

export const START_WAVE_AT_ME = 'START_WAVE_AT_ME';
export const STOP_WAVE_AT_ME = 'STOP_WAVE_AT_ME';

export const SET_ETH_BALANCE = 'SET_ETH_BALANCE';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
